version: '3'
services:

  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
 
    ports:
      - "8000:8000"  
    restart: "no"

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8000"  
    restart: "no"